name: check			# the name of this work flow
on: [push]  
# Specify the event that automatically triggers the workflow file. This example uses the push event, so that the jobs run every time someone pushes a change to the repository

jobs:  								# gather all the jobs that run in the workflow
  check-job:
    runs-on: ubuntu-latest   		# Set the type of machine to run on
    steps:
      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@chatbot.py
